CREATE DATABASE COLLEGEDB;
USE COLLEGEDB;
CREATE TABLE Student (
    StudentID INT PRIMARY KEY,
    StudentName VARCHAR(20) NOT NULL UNIQUE,
    DOB DATE NOT NULL,
    Gender VARCHAR(10) NOT NULL,
    DepartmentID INT NOT NULL
);
DESC student;
INSERT student VALUES("101","DEEPIKA","2008-05-02","FEMALE","1001");
SELECT*FROM student;
