CREATE DATABASE COLLEGEDB;
USE COLLEGEDB;
CREATE TABLE Student (
    StudentID INTEGER(20) PRIMARY KEY,
    StudentName VARCHAR(20) NOT NULL UNIQUE,
    DOB DATE NOT NULL,
    Gender VARCHAR(10) NOT NULL,
    DepartmentID INTEGER(10));
DESC Student;
INSERT  Student VALUES(101,"DEEPIKA","2008-05-02","FEMALE",1001);
DESC Student;
SELECT*FROM Student;
